/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poofootball.paneles;

import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

/**
 *
 * @author Adhisson
 */
public class DesignPreviewGUI extends javax.swing.JFrame {
    
    /**
     * Creates new form DesignPreviewGUI
     */
    public DesignPreviewGUI() {
        initComponents();
        
        try {
            URI uri = new URI("https://github.com/joseguzmann");
            class OpenUrlAction implements ActionListener {
                @Override
                public void actionPerformed(ActionEvent e) {
                    open(uri);
                }
            }
            btnJose.addActionListener(new OpenUrlAction());
        } catch (URISyntaxException ex) {
            Logger.getLogger(DesignPreviewGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdhisson = new javax.swing.JButton();
        btnDaniela = new javax.swing.JButton();
        btnJose = new javax.swing.JButton();

        setTitle("Design Preview [GUI]");

        btnAdhisson.setText("Adhisson Cedeño");
        btnAdhisson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdhissonActionPerformed(evt);
            }
        });

        btnDaniela.setText("Daniela Román");
        btnDaniela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanielaActionPerformed(evt);
            }
        });

        btnJose.setText("José Guzmán");
        btnJose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(btnAdhisson, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addGap(56, 56, 56)
                .addComponent(btnJose, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addGap(56, 56, 56)
                .addComponent(btnDaniela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnAdhisson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnJose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDaniela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(119, 119, 119))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDanielaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanielaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane,"Hola, mi usuario de GitHub es danielaro2" );
    }//GEN-LAST:event_btnDanielaActionPerformed

    private void btnJoseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnJoseActionPerformed
    {//GEN-HEADEREND:event_btnJoseActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(rootPane, "Hola, mi usuario de Github es joseguzmann\n");
        
        
    }//GEN-LAST:event_btnJoseActionPerformed

    private void btnAdhissonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdhissonActionPerformed
       
    }//GEN-LAST:event_btnAdhissonActionPerformed
    

    private static void open(URI uri) {
        if (Desktop.isDesktopSupported()) {
            try {
                Desktop.getDesktop().browse(uri);
            } catch (IOException e) {
                /* TODO: error handling */ }
        } else {
            /* TODO: error handling */ }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesignPreviewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesignPreviewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesignPreviewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesignPreviewGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesignPreviewGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdhisson;
    private javax.swing.JButton btnDaniela;
    private javax.swing.JButton btnJose;
    // End of variables declaration//GEN-END:variables
}
