/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poofootball.paneles;

import finalprojectpoofootballevents.*;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author jg175
 */
public class RegistrarPartidoPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegistrarPartidoPanel
     */
    public RegistrarPartidoPanel() {
        initComponents();
        actualizarListaEquipos();
        actualizarListaEstadios();
        lblErrorFecha.setVisible(false);
        lblErrorHora.setVisible(false);
        btnRegistrarPartido.setEnabled(false);
    }

    public void actualizarListaEquipos() {
        cmbEquipo1.removeAllItems();
        cmbEquipo2.removeAllItems();
        try {
            for (Equipo equipo : GUISistemaPartido.listaEquiposRegistrados) {
                cmbEquipo1.addItem(equipo.getNombre());
                cmbEquipo2.addItem(equipo.getNombre());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e.getStackTrace());
        }
    }

    public void actualizarListaEstadios() {
        cmbEstadio.removeAllItems();
        try {
            for (Estadio estadio : GUISistemaPartido.listaEstadiosRegistrados) {
                cmbEstadio.addItem(estadio.getNombreEstadio());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e.getStackTrace());
        }
    }

    public void actualizarListaEquiposGanadores() {
        cmbEquipoGanador.removeAllItems();
        if (cmbEquipo1.getSelectedIndex() != -1 && cmbEquipo2.getSelectedIndex() != -1) {
            cmbEquipoGanador.addItem(GUISistemaPartido.listaEquiposRegistrados.get(cmbEquipo1.getSelectedIndex()).getNombre());
            cmbEquipoGanador.addItem(GUISistemaPartido.listaEquiposRegistrados.get(cmbEquipo2.getSelectedIndex()).getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbEquipo1 = new javax.swing.JComboBox<>();
        cmbEstadio = new javax.swing.JComboBox<>();
        cmbEquipo2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbEquipoGanador = new javax.swing.JComboBox<>();
        btnRegistrarPartido = new javax.swing.JButton();
        lblErrorFecha = new javax.swing.JLabel();
        lblErrorHora = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Registrar Partido");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Fecha:");

        txtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFechaKeyReleased(evt);
            }
        });

        txtHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHoraKeyReleased(evt);
            }
        });

        jLabel3.setText("Hora:");

        jLabel4.setText("Equipo 1:");

        jLabel5.setText("Equipo 2:");

        jLabel6.setText("Estadio:");

        cmbEquipo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbEquipo1ItemStateChanged(evt);
            }
        });
        cmbEquipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEquipo1ActionPerformed(evt);
            }
        });

        cmbEquipo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEquipo2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Equipo ganador:");

        btnRegistrarPartido.setText("Registrar partido");
        btnRegistrarPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPartidoActionPerformed(evt);
            }
        });

        lblErrorFecha.setForeground(java.awt.Color.red);
        lblErrorFecha.setText("Ingrese una fecha válida formato YYYY-MM-DD");

        lblErrorHora.setForeground(java.awt.Color.red);
        lblErrorHora.setText("Ingrese una hora válida HH:MM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbEquipo2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbEstadio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(cmbEquipo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(cmbEquipoGanador, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorHora, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lblErrorFecha)
                        .addGap(56, 56, 56))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(btnRegistrarPartido)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblErrorFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblErrorHora, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbEquipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbEquipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(cmbEquipoGanador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cmbEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnRegistrarPartido)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(234, 234, 234))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarPartidoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRegistrarPartidoActionPerformed
    {//GEN-HEADEREND:event_btnRegistrarPartidoActionPerformed
        // TODO add your handling code here:

        String fecha = txtFecha.getText();
        String hora = txtHora.getText();
        Equipo ganador = null;
        Equipo equipo1 = GUISistemaPartido.listaEquiposRegistrados.get(cmbEquipo1.getSelectedIndex());
        Equipo equipo2 = GUISistemaPartido.listaEquiposRegistrados.get(cmbEquipo2.getSelectedIndex());
        if (cmbEquipoGanador.getSelectedIndex() == 0) {
            ganador = equipo1;
        } else if (cmbEquipoGanador.getSelectedIndex() == 1) {
            ganador = equipo2;
        }
        Estadio estadio = GUISistemaPartido.listaEstadiosRegistrados.get(cmbEstadio.getSelectedIndex());
        Partido partido = new Partido(fecha, ganador, hora, equipo1, equipo2, estadio);
        GUISistemaPartido.listaPartidosRegistrados.add(partido);
        try (MiObjectOutputStream salida = new MiObjectOutputStream("registroPartidos.txt");) {
            salida.writeObject(partido);
            JOptionPane.showMessageDialog(null, "Se registró correctamente");
            salida.close();
            
        } catch (IOException ioe) {
            System.err.println("No se creo el partido" + ioe);
        }
    }//GEN-LAST:event_btnRegistrarPartidoActionPerformed

    private void cmbEquipo1ItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_cmbEquipo1ItemStateChanged
    {//GEN-HEADEREND:event_cmbEquipo1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEquipo1ItemStateChanged

    private void cmbEquipo1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbEquipo1ActionPerformed
    {//GEN-HEADEREND:event_cmbEquipo1ActionPerformed
        // TODO add your handling code here:
        actualizarListaEquiposGanadores();
    }//GEN-LAST:event_cmbEquipo1ActionPerformed

    private void cmbEquipo2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbEquipo2ActionPerformed
    {//GEN-HEADEREND:event_cmbEquipo2ActionPerformed
        // TODO add your handling code here:
        actualizarListaEquiposGanadores();
    }//GEN-LAST:event_cmbEquipo2ActionPerformed

    private void txtFechaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyReleased
        // TODO add your handling code here:
        if (Validadores.validadorFecha(txtFecha.getText())) {
            lblErrorFecha.setVisible(false);
            btnRegistrarPartido.setEnabled(true);
        } else {
            lblErrorFecha.setVisible(true);
            btnRegistrarPartido.setEnabled(false);
        }

    }//GEN-LAST:event_txtFechaKeyReleased

    private void txtHoraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoraKeyReleased
        // TODO add your handling code here:

        if (Validadores.validadorHora(txtHora.getText())) {
            lblErrorHora.setVisible(false);
            btnRegistrarPartido.setEnabled(true);
        } else {
            lblErrorHora.setVisible(true);
            btnRegistrarPartido.setEnabled(false);
        }

    }//GEN-LAST:event_txtHoraKeyReleased

    private void limpiarPanel() {
        txtFecha.setText(null);
        txtHora.setText(null);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarPartido;
    private javax.swing.JComboBox<String> cmbEquipo1;
    private javax.swing.JComboBox<String> cmbEquipo2;
    private javax.swing.JComboBox<String> cmbEquipoGanador;
    private javax.swing.JComboBox<String> cmbEstadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblErrorFecha;
    private javax.swing.JLabel lblErrorHora;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    // End of variables declaration//GEN-END:variables
}
