/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poofootball.paneles;

import finalprojectpoofootballevents.Equipo;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniela Roman
 */
public class VerEquiposPanel extends javax.swing.JPanel {

    DefaultTableModel dtmTabla;

    /**
     * Creates new form VerEquipos
     */
    public VerEquiposPanel() {
        initComponents();
        dtmTabla = new DefaultTableModel();
        dtmTabla.addColumn("Nombre");
        dtmTabla.addColumn("Año Fundacion");
        tblPresentarEquipos.setModel(dtmTabla);
    }

    public void verEquiposTabla() {
        try {
            dtmTabla.setRowCount(0);
            for (Equipo e : GUISistemaPartido.listaEquiposRegistrados) {
                dtmTabla.addRow(new Object[]{e.getNombre(), e.getAnioFundacion()});
            }
        } catch (Exception e) {

        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPresentarEquipos = new javax.swing.JTable();

        tblPresentarEquipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPresentarEquipos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPresentarEquipos;
    // End of variables declaration//GEN-END:variables
}
